// All rights reserved ADENEO EMBEDDED 2010
/*
===============================================================================
*             Texas Instruments OMAP(TM) Platform Software
* (c) Copyright Texas Instruments, Incorporated. All Rights Reserved.
*
* Use of this software is controlled by the terms and conditions found
* in the license agreement under which this software has been supplied.
*
===============================================================================
*/
//
//  File:  bsp_cfg.c
//
#include "bsp.h"
#include "soc_cfg.h"
#include "oal_padcfg.h"

#define SAFE_INPUT_PULLUP   (INPUT_ENABLED | PULLUP_RESISTOR | PULL_RESISTOR_ENABLED | MUXMODE(SAFE_MODE))
#define PAD_ENTRY(x,y)      {PAD_ID(x),y,0},
#define WKUP_PAD_ENTRY(x,y) {WKUP_PAD_ID(x),y,0},


//------------------------------------------------------------------------------
//  Pad configuration
//------------------------------------------------------------------------------

#define ALL_ALLOWED_PADS \
{       \
    /*      PAD name             Default config when PIN is released (not request by any driver or the OAL)*/           \
    PAD_ENTRY(SDRC_D0             ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D1             ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D2             ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D3             ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D4             ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D5             ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D6             ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D7             ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D8             ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D9             ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D10            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D11            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D12            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D13            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D14            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D15            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D16            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D17            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D18            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D19            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D20            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D21            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D22            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D23            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D24            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D25            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D26            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D27            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D28            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D29            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D30            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D31            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_CLK            ,INPUT_DISABLED | MUXMODE(0))    \
    PAD_ENTRY(SDRC_DQS0           ,INPUT_DISABLED | MUXMODE(0))    \
    PAD_ENTRY(SDRC_DQS1           ,INPUT_DISABLED | MUXMODE(0))    \
    PAD_ENTRY(SDRC_DQS2           ,INPUT_DISABLED | MUXMODE(0))    \
    PAD_ENTRY(SDRC_DQS3           ,INPUT_DISABLED | MUXMODE(0))    \
    PAD_ENTRY(SDRC_CKE0           ,INPUT_DISABLED | MUXMODE(0))    \
    /*GPMC pads (Nand, nor, external LAN  etc.)*/                   \
    PAD_ENTRY(GPMC_A1             ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(GPMC_A2             ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(GPMC_A3             ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(GPMC_A4             ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(GPMC_A5             ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(GPMC_A6             ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(GPMC_A7             ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(GPMC_A8             ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(GPMC_A9             ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(GPMC_A10            ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(GPMC_D0             ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(GPMC_D1             ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(GPMC_D2             ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(GPMC_D3             ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(GPMC_D4             ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(GPMC_D5             ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(GPMC_D6             ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(GPMC_D7             ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(GPMC_D8             ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(GPMC_D9             ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(GPMC_D10            ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(GPMC_D11            ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(GPMC_D12            ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(GPMC_D13            ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(GPMC_D14            ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(GPMC_D15            ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(GPMC_nCS0           ,SAFE_INPUT_PULLUP)               \
    PAD_ENTRY(GPMC_nCS1           ,SAFE_INPUT_PULLUP)               \
    PAD_ENTRY(GPMC_nCS2           ,SAFE_INPUT_PULLUP)               \
    PAD_ENTRY(GPMC_nCS3           ,SAFE_INPUT_PULLUP)               \
    PAD_ENTRY(GPMC_nCS4           ,SAFE_INPUT_PULLUP)               \
    PAD_ENTRY(GPMC_nCS5           ,SAFE_INPUT_PULLUP)               \
    PAD_ENTRY(GPMC_nCS6           ,SAFE_INPUT_PULLUP)               \
    PAD_ENTRY(GPMC_nCS7           ,SAFE_INPUT_PULLUP)               \
    PAD_ENTRY(GPMC_CLK            ,SAFE_INPUT_PULLUP)               \
    PAD_ENTRY(GPMC_nADV_ALE       ,SAFE_INPUT_PULLUP)               \
    PAD_ENTRY(GPMC_nOE            ,SAFE_INPUT_PULLUP)               \
    PAD_ENTRY(GPMC_nWE            ,SAFE_INPUT_PULLUP)               \
    PAD_ENTRY(GPMC_nBE0_CLE       ,SAFE_INPUT_PULLUP)               \
    PAD_ENTRY(GPMC_nBE1           ,SAFE_INPUT_PULLUP)               \
    PAD_ENTRY(GPMC_nWP            ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(GPMC_WAIT0          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(GPMC_WAIT1          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(GPMC_WAIT2          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(GPMC_WAIT3          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    /*Other pads                                                 */ \
    PAD_ENTRY(DSS_PCLK            ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(DSS_HSYNC           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(DSS_VSYNC           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(DSS_ACBIAS          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(DSS_DATA0           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(DSS_DATA1           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(DSS_DATA2           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(DSS_DATA3           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(DSS_DATA4           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(DSS_DATA5           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(DSS_DATA6           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(DSS_DATA7           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(DSS_DATA8           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(DSS_DATA9           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(DSS_DATA10          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(DSS_DATA11          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(DSS_DATA12          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(DSS_DATA13          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(DSS_DATA14          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(DSS_DATA15          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(DSS_DATA16          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(DSS_DATA17          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(DSS_DATA18          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(DSS_DATA19          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(DSS_DATA20          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(DSS_DATA21          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(DSS_DATA22          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(DSS_DATA23          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MCBSP2_FSX          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MCBSP2_CLKX         ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MCBSP2_DR           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MCBSP2_DX           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MMC1_CLK            ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MMC1_CMD            ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MMC1_DAT0           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MMC1_DAT1           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MMC1_DAT2           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MMC1_DAT3           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MMC1_DAT4           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MMC1_DAT5           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MMC1_DAT6           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MMC1_DAT7           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MMC2_CLK            ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MMC2_CMD            ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MMC2_DAT0           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MMC2_DAT1           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MMC2_DAT2           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MMC2_DAT3           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MMC2_DAT4           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MMC2_DAT5           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MMC2_DAT6           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MMC2_DAT7           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MCBSP3_DX           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MCBSP3_DR           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MCBSP3_CLKX         ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MCBSP3_FSX          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(UART2_CTS           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(UART2_RTS           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(UART2_TX            ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(UART2_RX            ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(UART1_TX            ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(UART1_RTS           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(UART1_CTS           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(UART1_RX            ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MCBSP4_CLKX         ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MCBSP4_DR           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MCBSP4_DX           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MCBSP4_FSX          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MCBSP1_CLKR         ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MCBSP1_FSR          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MCBSP1_DX           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MCBSP1_DR           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MCBSP_CLKS          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MCBSP1_FSX          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MCBSP1_CLKX         ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(UART3_CTS_RCTX      ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(UART3_RTS_SD        ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(UART3_RX_IRRX       ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(UART3_TX_IRTX       ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(I2C1_SCL            ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(I2C1_SDA            ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(I2C2_SCL            ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(I2C2_SDA            ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(I2C3_SCL            ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(I2C3_SDA            ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(HDQ_SIO             ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MCSPI1_CLK          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MCSPI1_SIMO         ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MCSPI1_SOMI         ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MCSPI1_CS0          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MCSPI1_CS1          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MCSPI1_CS2          ,INPUT_DISABLED | MUXMODE(4))     \
    PAD_ENTRY(MCSPI1_CS3          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MCSPI2_CLK          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MCSPI2_SIMO         ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MCSPI2_SOMI         ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(MCSPI2_CS0          ,INPUT_DISABLED | MUXMODE(4))     \
    PAD_ENTRY(MCSPI2_CS1          ,INPUT_DISABLED | MUXMODE(4))     \
    PAD_ENTRY(SYS_NIRQ            ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(CCDC_PCLK           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(CCDC_FIELD          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(CCDC_HD             ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(CCDC_VD             ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(CCDC_WEN            ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(CCDC_DATA0          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(CCDC_DATA1          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(CCDC_DATA2          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(CCDC_DATA3          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(CCDC_DATA4          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(CCDC_DATA5          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(CCDC_DATA6          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(CCDC_DATA7          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(RMII_MDIO_DATA      ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(RMII_MDIO_CLK       ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(RMII_RXD0           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(RMII_RXD1           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(RMII_CRS_DV         ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(RMII_RXER           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(RMII_TXD0           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(RMII_TXD1           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(RMII_TXEN           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(RMII_50MHZ_CLK      ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(USB0_DRVVBUS        ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(HECC1_TXD           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(HECC1_RXD           ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(SDRC_DQS0N          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(SDRC_DQS1N          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(SDRC_DQS2N          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(SDRC_DQS3N          ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(SDRC_STRBEN_DLY0    ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(SDRC_STRBEN_DLY1    ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(ETK_CLK             ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(ETK_CTL             ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(ETK_D0              ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(ETK_D1              ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(ETK_D2              ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(ETK_D3              ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(ETK_D4              ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(ETK_D5              ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(ETK_D6              ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(ETK_D7              ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(ETK_D8              ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(ETK_D9              ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(ETK_D10             ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(ETK_D11             ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(ETK_D12             ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(ETK_D13             ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(ETK_D14             ,RELEASED_PAD_DEFAULT_CONFIG)     \
    PAD_ENTRY(ETK_D15             ,RELEASED_PAD_DEFAULT_CONFIG)     \
    WKUP_PAD_ENTRY(I2C4_SCL       ,INPUT_ENABLED | PULL_RESISTOR_DISABLED | MUXMODE(0))   \
    WKUP_PAD_ENTRY(I2C4_SDA       ,INPUT_ENABLED | PULL_RESISTOR_DISABLED | MUXMODE(0))   \
    WKUP_PAD_ENTRY(SYS_32K        ,INPUT_ENABLED | PULL_RESISTOR_DISABLED | MUXMODE(0))   \
    WKUP_PAD_ENTRY(SYS_BOOT0      ,RELEASED_PAD_DEFAULT_CONFIG)     \
    WKUP_PAD_ENTRY(SYS_BOOT1      ,RELEASED_PAD_DEFAULT_CONFIG)     \
    WKUP_PAD_ENTRY(SYS_BOOT2      ,RELEASED_PAD_DEFAULT_CONFIG)     \
    WKUP_PAD_ENTRY(SYS_BOOT3      ,RELEASED_PAD_DEFAULT_CONFIG)     \
    WKUP_PAD_ENTRY(SYS_BOOT4      ,RELEASED_PAD_DEFAULT_CONFIG)     \
    WKUP_PAD_ENTRY(SYS_BOOT5      ,RELEASED_PAD_DEFAULT_CONFIG)     \
    WKUP_PAD_ENTRY(SYS_BOOT6      ,RELEASED_PAD_DEFAULT_CONFIG)     \
    END_OF_PAD_ARRAY                                                \
}

#define SDRC_PADS \
    PAD_ENTRY(SDRC_D0             ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D1             ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D2             ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D3             ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D4             ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D5             ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D6             ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D7             ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D8             ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D9             ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D10            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D11            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D12            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D13            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D14            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D15            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D16            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D17            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D18            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D19            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D20            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D21            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D22            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D23            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D24            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D25            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D26            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D27            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D28            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D29            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D30            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_D31            ,INPUT_ENABLED | MUXMODE(0) )    \
    PAD_ENTRY(SDRC_CLK            ,INPUT_DISABLED | MUXMODE(0))    \
    PAD_ENTRY(SDRC_DQS0           ,INPUT_DISABLED | MUXMODE(0))    \
    PAD_ENTRY(SDRC_DQS1           ,INPUT_DISABLED | MUXMODE(0))    \
    PAD_ENTRY(SDRC_DQS2           ,INPUT_DISABLED | MUXMODE(0))    \
    PAD_ENTRY(SDRC_DQS3           ,INPUT_DISABLED | MUXMODE(0))    \
    PAD_ENTRY(SDRC_CKE0           ,INPUT_DISABLED | MUXMODE(0))    

#define DSS_PADS  \
    PAD_ENTRY(DSS_PCLK            ,INPUT_DISABLED | MUXMODE(0))     	\
    PAD_ENTRY(DSS_HSYNC           ,INPUT_DISABLED | MUXMODE(0))     	\
    PAD_ENTRY(DSS_VSYNC           ,INPUT_DISABLED | MUXMODE(0))     	\
    PAD_ENTRY(DSS_ACBIAS          ,INPUT_DISABLED | MUXMODE(0))     	\
    PAD_ENTRY(DSS_DATA0           ,INPUT_DISABLED | MUXMODE(0))     	\
    PAD_ENTRY(DSS_DATA1           ,INPUT_DISABLED | MUXMODE(0))     	\
    PAD_ENTRY(DSS_DATA2           ,INPUT_DISABLED | MUXMODE(0))     	\
    PAD_ENTRY(DSS_DATA3           ,INPUT_DISABLED | MUXMODE(0))     	\
    PAD_ENTRY(DSS_DATA4           ,INPUT_DISABLED | MUXMODE(0))     	\
    PAD_ENTRY(DSS_DATA5           ,INPUT_DISABLED | MUXMODE(0))     	\
    PAD_ENTRY(DSS_DATA6           ,INPUT_DISABLED | MUXMODE(0))     	\
    PAD_ENTRY(DSS_DATA7           ,INPUT_DISABLED | MUXMODE(0))     	\
    PAD_ENTRY(DSS_DATA8           ,INPUT_DISABLED | MUXMODE(0))     	\
    PAD_ENTRY(DSS_DATA9           ,INPUT_DISABLED | MUXMODE(0))     	\
    PAD_ENTRY(DSS_DATA10          ,INPUT_DISABLED | MUXMODE(0))     	\
    PAD_ENTRY(DSS_DATA11          ,INPUT_DISABLED | MUXMODE(0))     	\
    PAD_ENTRY(DSS_DATA12          ,INPUT_DISABLED | MUXMODE(0))     	\
    PAD_ENTRY(DSS_DATA13          ,INPUT_DISABLED | MUXMODE(0))     	\
    PAD_ENTRY(DSS_DATA14          ,INPUT_DISABLED | MUXMODE(0))     	\
    PAD_ENTRY(DSS_DATA15          ,INPUT_DISABLED | MUXMODE(0))     	\
    PAD_ENTRY(DSS_DATA16          ,INPUT_DISABLED | MUXMODE(0))     	\
    PAD_ENTRY(DSS_DATA17          ,INPUT_DISABLED | MUXMODE(0))     	\
    PAD_ENTRY(DSS_DATA18          ,INPUT_DISABLED | MUXMODE(0))     	\
    PAD_ENTRY(DSS_DATA19          ,INPUT_DISABLED | MUXMODE(0))     	\
    PAD_ENTRY(DSS_DATA20          ,INPUT_DISABLED | MUXMODE(0))     	\
    PAD_ENTRY(DSS_DATA21          ,INPUT_DISABLED | MUXMODE(0))     	\
    PAD_ENTRY(DSS_DATA22          ,INPUT_DISABLED | MUXMODE(0))			\
    PAD_ENTRY(DSS_DATA23          ,INPUT_DISABLED | MUXMODE(0))			\
	PAD_ENTRY(MCSPI2_CS0,   INPUT_DISABLED | MUXMODE(4)) /* GPIO 181 */	\
    PAD_ENTRY(MCSPI2_CS1,   INPUT_DISABLED | MUXMODE(4)) /* GPIO 182 */ \
    PAD_ENTRY(MCSPI1_CS2,   INPUT_DISABLED | MUXMODE(4)) /* GPIO 176 */    

#define GPMC_PADS \
    PAD_ENTRY(GPMC_A1,          INPUT_DISABLED | MUXMODE(0))     \
    PAD_ENTRY(GPMC_A2,          INPUT_DISABLED | MUXMODE(0))     \
    PAD_ENTRY(GPMC_A3,          INPUT_DISABLED | MUXMODE(0))     \
    PAD_ENTRY(GPMC_A4,          INPUT_DISABLED | MUXMODE(0))     \
    PAD_ENTRY(GPMC_A5,          INPUT_DISABLED | MUXMODE(0))     \
    PAD_ENTRY(GPMC_A6,          INPUT_DISABLED | MUXMODE(0))     \
    PAD_ENTRY(GPMC_A7,          INPUT_DISABLED | MUXMODE(0))     \
    PAD_ENTRY(GPMC_A8,          INPUT_DISABLED | MUXMODE(0))     \
    PAD_ENTRY(GPMC_A9,          INPUT_DISABLED | MUXMODE(0))     \
    PAD_ENTRY(GPMC_A10,         INPUT_DISABLED | MUXMODE(0))     \
    PAD_ENTRY(GPMC_D0,          INPUT_ENABLED | MUXMODE(0))      \
    PAD_ENTRY(GPMC_D1,          INPUT_ENABLED | MUXMODE(0))      \
    PAD_ENTRY(GPMC_D2,          INPUT_ENABLED | MUXMODE(0))      \
    PAD_ENTRY(GPMC_D3,          INPUT_ENABLED | MUXMODE(0))      \
    PAD_ENTRY(GPMC_D4,          INPUT_ENABLED | MUXMODE(0))      \
    PAD_ENTRY(GPMC_D5,          INPUT_ENABLED | MUXMODE(0))      \
    PAD_ENTRY(GPMC_D6,          INPUT_ENABLED | MUXMODE(0))      \
    PAD_ENTRY(GPMC_D7,          INPUT_ENABLED | MUXMODE(0))      \
    PAD_ENTRY(GPMC_D8,          INPUT_ENABLED | MUXMODE(0))      \
    PAD_ENTRY(GPMC_D9,          INPUT_ENABLED | MUXMODE(0))      \
    PAD_ENTRY(GPMC_D10,         INPUT_ENABLED | MUXMODE(0))      \
    PAD_ENTRY(GPMC_D11,         INPUT_ENABLED | MUXMODE(0))      \
    PAD_ENTRY(GPMC_D12,         INPUT_ENABLED | MUXMODE(0))      \
    PAD_ENTRY(GPMC_D13,         INPUT_ENABLED | MUXMODE(0))      \
    PAD_ENTRY(GPMC_D14,         INPUT_ENABLED | MUXMODE(0))      \
    PAD_ENTRY(GPMC_D15,         INPUT_ENABLED | MUXMODE(0))      \
    PAD_ENTRY(GPMC_nCS0,        INPUT_DISABLED | MUXMODE(0))     \
    PAD_ENTRY(GPMC_nCS1,        INPUT_DISABLED | MUXMODE(0))     \
    PAD_ENTRY(GPMC_nCS2,        INPUT_DISABLED | MUXMODE(0))     \
    PAD_ENTRY(GPMC_nCS3,        INPUT_DISABLED | MUXMODE(0))     \
    PAD_ENTRY(GPMC_nCS5,        INPUT_DISABLED | MUXMODE(0))     \
    PAD_ENTRY(GPMC_nCS7,        INPUT_DISABLED | MUXMODE(0))     \
    PAD_ENTRY(GPMC_CLK,         INPUT_DISABLED | MUXMODE(0))     \
    PAD_ENTRY(GPMC_nADV_ALE,    INPUT_DISABLED | MUXMODE(0))     \
    PAD_ENTRY(GPMC_nOE,         INPUT_DISABLED | MUXMODE(0))     \
    PAD_ENTRY(GPMC_nWE,         INPUT_DISABLED | MUXMODE(0))     \
    PAD_ENTRY(GPMC_nBE0_CLE,    INPUT_DISABLED | MUXMODE(0))     \
    PAD_ENTRY(GPMC_nWP,         INPUT_DISABLED | MUXMODE(0))     \
    PAD_ENTRY(GPMC_WAIT0,       INPUT_ENABLED | MUXMODE(0))      \
    PAD_ENTRY(GPMC_WAIT1,       INPUT_ENABLED | MUXMODE(0))      

#define UART1_PADS \
    PAD_ENTRY(UART1_TX , INPUT_DISABLED | MUXMODE(0))      \
    PAD_ENTRY(UART1_RTS, INPUT_DISABLED | MUXMODE(0))      \
    PAD_ENTRY(UART1_CTS, INPUT_ENABLED | PULL_RESISTOR_ENABLED | PULLUP_RESISTOR | MUXMODE(0))      \
    PAD_ENTRY(UART1_RX , INPUT_ENABLED | PULL_RESISTOR_ENABLED | PULLUP_RESISTOR | MUXMODE(0))     

#define UART2_PADS \
    PAD_ENTRY(UART2_TX , INPUT_DISABLED | MUXMODE(0))      \
    PAD_ENTRY(UART2_RTS, INPUT_DISABLED | MUXMODE(0))      \
    PAD_ENTRY(UART2_CTS, INPUT_ENABLED | PULL_RESISTOR_ENABLED | PULLUP_RESISTOR | MUXMODE(0))      \
    PAD_ENTRY(UART2_RX , INPUT_ENABLED | PULL_RESISTOR_ENABLED | PULLUP_RESISTOR | MUXMODE(0))     

#define UART3_PADS \
    PAD_ENTRY(UART3_TX_IRTX , INPUT_DISABLED | MUXMODE(0))      \
    PAD_ENTRY(UART3_RTS_SD  , INPUT_DISABLED | MUXMODE(0))      \
    PAD_ENTRY(UART3_CTS_RCTX, INPUT_ENABLED | PULL_RESISTOR_ENABLED | PULLUP_RESISTOR | MUXMODE(0))       \
    PAD_ENTRY(UART3_RX_IRRX , INPUT_ENABLED | PULL_RESISTOR_ENABLED | PULLUP_RESISTOR | MUXMODE(0))       

#define MMC1_PADS   \
    PAD_ENTRY(MMC1_CLK, INPUT_ENABLED | PULL_RESISTOR_ENABLED | PULLUP_RESISTOR | MUXMODE(0))   \
	PAD_ENTRY(MMC1_CMD, INPUT_ENABLED | MUXMODE(0))                                             \
	PAD_ENTRY(MMC1_DAT0, INPUT_ENABLED | MUXMODE(0))	                                        \
	PAD_ENTRY(MMC1_DAT1, INPUT_ENABLED | MUXMODE(0))	                                        \
	PAD_ENTRY(MMC1_DAT2, INPUT_ENABLED | MUXMODE(0))	                                        \
	PAD_ENTRY(MMC1_DAT3, INPUT_ENABLED | MUXMODE(0))	                                        \
	PAD_ENTRY(MMC1_DAT4, INPUT_ENABLED | PULL_RESISTOR_ENABLED | PULLUP_RESISTOR | MUXMODE(4))  \
	PAD_ENTRY(MMC1_DAT5, INPUT_ENABLED | PULL_RESISTOR_ENABLED | PULLUP_RESISTOR | MUXMODE(4))

#define MMC2_PADS	\
    PAD_ENTRY(MMC2_CLK,  INPUT_ENABLED | PULL_RESISTOR_ENABLED | PULLUP_RESISTOR | MUXMODE(0))  \
	PAD_ENTRY(MMC2_CMD,  INPUT_ENABLED | MUXMODE(0))                                            \
	PAD_ENTRY(MMC2_DAT0, INPUT_ENABLED | MUXMODE(0))	                                        \
	PAD_ENTRY(MMC2_DAT1, INPUT_ENABLED | MUXMODE(0))	                                        \
	PAD_ENTRY(MMC2_DAT2, INPUT_ENABLED | MUXMODE(0))	                                        \
	PAD_ENTRY(MMC2_DAT3, INPUT_ENABLED | MUXMODE(0))											\
	PAD_ENTRY(MCSPI1_CS1,INPUT_ENABLED | PULL_RESISTOR_ENABLED | PULLUP_RESISTOR | MUXMODE(4))  
	// Enable this pin mux if WP is needed for SDHC/MMC slot 2 in addition to enabling registry settings in sdhc.reg
	//PAD_ENTRY(MCSPI1_CS2,INPUT_ENABLED | PULL_RESISTOR_ENABLED | PULLUP_RESISTOR | MUXMODE(4)) /* GPIO 176 */    

#define I2C1_PADS   \
    PAD_ENTRY(I2C1_SCL, INPUT_ENABLED | PULL_RESISTOR_DISABLED | MUXMODE(0))   \
    PAD_ENTRY(I2C1_SDA, INPUT_ENABLED | PULL_RESISTOR_DISABLED | MUXMODE(0))   

#define I2C2_PADS   \
    PAD_ENTRY(I2C2_SCL, INPUT_ENABLED | PULL_RESISTOR_DISABLED | MUXMODE(0))   \
    PAD_ENTRY(I2C2_SDA, INPUT_ENABLED | PULL_RESISTOR_DISABLED | MUXMODE(0))   

#define I2C3_PADS   \
    PAD_ENTRY(I2C3_SCL, INPUT_ENABLED | PULL_RESISTOR_DISABLED | MUXMODE(0))   \
    PAD_ENTRY(I2C3_SDA, INPUT_ENABLED | PULL_RESISTOR_DISABLED | MUXMODE(0))   

#define I2C4_PADS   \
    WKUP_PAD_ENTRY(I2C4_SCL, INPUT_ENABLED | PULL_RESISTOR_DISABLED | MUXMODE(0))   \
    WKUP_PAD_ENTRY(I2C4_SDA, INPUT_ENABLED | PULL_RESISTOR_DISABLED | MUXMODE(0))   

#define ETHERNET_PADS   \
    PAD_ENTRY(RMII_MDIO_DATA	, INPUT_ENABLED | PULL_RESISTOR_ENABLED | PULLUP_RESISTOR | MUXMODE(0))	\
    PAD_ENTRY(RMII_MDIO_CLK	    , INPUT_ENABLED | PULL_RESISTOR_ENABLED | PULLUP_RESISTOR | MUXMODE(0))	\
    PAD_ENTRY(RMII_RXD0		    , INPUT_ENABLED | PULL_RESISTOR_ENABLED | PULLUP_RESISTOR | MUXMODE(0))	\
    PAD_ENTRY(RMII_RXD1		    , INPUT_ENABLED | PULL_RESISTOR_ENABLED | PULLUP_RESISTOR | MUXMODE(0))	\
    PAD_ENTRY(RMII_CRS_DV		, INPUT_ENABLED | PULL_RESISTOR_ENABLED | PULLUP_RESISTOR | MUXMODE(0))	\
    PAD_ENTRY(RMII_RXER 		, INPUT_ENABLED | PULL_RESISTOR_ENABLED | PULLUP_RESISTOR | MUXMODE(0))	\
    PAD_ENTRY(RMII_50MHZ_CLK	, INPUT_ENABLED | PULL_RESISTOR_ENABLED | PULLUP_RESISTOR | MUXMODE(0)) \
    PAD_ENTRY(RMII_TXD0 		, INPUT_DISABLED | PULL_RESISTOR_DISABLED | MUXMODE(0))                 \
    PAD_ENTRY(RMII_TXD1 		, INPUT_DISABLED | PULL_RESISTOR_DISABLED | MUXMODE(0))                 \
    PAD_ENTRY(RMII_TXEN 		, INPUT_DISABLED | PULL_RESISTOR_DISABLED | MUXMODE(0))                 


#define MCSPI1_PADS \
    PAD_ENTRY(MCSPI1_CS0, INPUT_DISABLED | PULL_RESISTOR_DISABLED | MUXMODE(0)) \
    PAD_ENTRY(MCSPI1_SOMI,INPUT_DISABLED | PULL_RESISTOR_DISABLED | MUXMODE(0)) \
    PAD_ENTRY(MCSPI1_SIMO,INPUT_DISABLED | PULL_RESISTOR_DISABLED | MUXMODE(0)) \
    PAD_ENTRY(MCSPI1_CLK, INPUT_DISABLED | PULL_RESISTOR_DISABLED | MUXMODE(0)) 

#define MCBSP1_PADS \
    PAD_ENTRY(MCBSP1_CLKX, INPUT_ENABLED | PULL_RESISTOR_DISABLED | MUXMODE(0)) \
    PAD_ENTRY(MCBSP1_FSX,  INPUT_ENABLED | PULL_RESISTOR_DISABLED | MUXMODE(0)) \
    PAD_ENTRY(MCBSP1_DR,   INPUT_ENABLED | PULL_RESISTOR_DISABLED | MUXMODE(0)) \
    PAD_ENTRY(MCBSP1_DX,   INPUT_ENABLED | PULL_RESISTOR_DISABLED | MUXMODE(0))

#define MCBSP2_PADS \
    PAD_ENTRY(MCBSP2_CLKX, INPUT_ENABLED | PULL_RESISTOR_DISABLED | MUXMODE(0)) \
    PAD_ENTRY(MCBSP2_FSX,  INPUT_ENABLED | PULL_RESISTOR_DISABLED | MUXMODE(0)) \
    PAD_ENTRY(MCBSP2_DR,   INPUT_ENABLED | PULL_RESISTOR_DISABLED | MUXMODE(0)) \
    PAD_ENTRY(MCBSP2_DX,   INPUT_ENABLED | PULL_RESISTOR_DISABLED | MUXMODE(0))

#define HECC_PADS   \
    PAD_ENTRY(HECC1_TXD, INPUT_DISABLED | PULL_RESISTOR_DISABLED | MUXMODE(0))  \
    PAD_ENTRY(HECC1_RXD, INPUT_ENABLED | PULL_RESISTOR_DISABLED | MUXMODE(0))   

#define GPIO_PADS   \
    PAD_ENTRY(GPMC_nCS4,    INPUT_ENABLED | PULL_RESISTOR_ENABLED | PULLUP_RESISTOR | MUXMODE(4)) /* GPIO_55  */    \
    PAD_ENTRY(MCBSP1_FSR,   INPUT_ENABLED | PULL_RESISTOR_ENABLED | PULLUP_RESISTOR | MUXMODE(4)) /* GPIO_157 */    \
    PAD_ENTRY(MCBSP_CLKS,   INPUT_ENABLED | PULL_RESISTOR_ENABLED | PULLUP_RESISTOR | MUXMODE(4)) /* GPIO 160 */    \
    PAD_ENTRY(SYS_NIRQ,     INPUT_ENABLED | PULL_RESISTOR_ENABLED | PULLUP_RESISTOR | MUXMODE(4)) /* GPIO 0	  */    \
    PAD_ENTRY(GPMC_WAIT3,   INPUT_ENABLED | PULL_RESISTOR_ENABLED | PULLUP_RESISTOR | MUXMODE(4)) /* GPIO_65  */

//    PAD_ENTRY(MMC1_DAT4,    INPUT_ENABLED | PULL_RESISTOR_ENABLED | PULLUP_RESISTOR | MUXMODE(4)) /* GPIO 126 */    
//    PAD_ENTRY(MMC1_DAT6,    INPUT_ENABLED | PULL_RESISTOR_ENABLED | PULLUP_RESISTOR | MUXMODE(4)) /* GPIO 128 */    
//    PAD_ENTRY(MMC1_DAT7,    INPUT_ENABLED | PULL_RESISTOR_ENABLED | PULLUP_RESISTOR | MUXMODE(4)) /* GPIO 129 */    
//    PAD_ENTRY(GPMC_WAIT2,   INPUT_ENABLED | PULL_RESISTOR_ENABLED | PULLUP_RESISTOR | MUXMODE(4)) /* GPIO_64  */    
//    PAD_ENTRY(GPMC_nBE1,    INPUT_ENABLED | PULL_RESISTOR_ENABLED | PULLDOWN_RESISTOR | MUXMODE(4))/* GPIO_61 */    
        
#define USBH1_PADS	\
	PAD_ENTRY(GPMC_nCS6, INPUT_DISABLED | PULL_RESISTOR_DISABLED | MUXMODE(4))  /* GPIO 57	  */ \
    PAD_ENTRY(ETK_CTL,   INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(3)) 	/* USB1_CLK	  */ \
    PAD_ENTRY(ETK_CLK,   INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(3)) 	/* HSUSB1_STP */ \
    PAD_ENTRY(ETK_D0,    INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(3)) 	/* HSUSB1_D0  */ \
    PAD_ENTRY(ETK_D1,    INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(3)) 	/* HSUSB1_D1  */ \
    PAD_ENTRY(ETK_D2,    INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(3)) 	/* HSUSB1_D2  */ \
    PAD_ENTRY(ETK_D3,    INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(3)) 	/* HSUSB1_D7  */ \
    PAD_ENTRY(ETK_D4,    INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(3)) 	/* HSUSB1_D4  */ \
    PAD_ENTRY(ETK_D5,    INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(3)) 	/* HSUSB1_D5  */ \
    PAD_ENTRY(ETK_D6,    INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(3)) 	/* HSUSB1_D6  */ \
    PAD_ENTRY(ETK_D7,    INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(3)) 	/* HSUSB1_D3  */ \
    PAD_ENTRY(ETK_D8,    INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(3)) 	/* HSUSB1_DIR */ \
	PAD_ENTRY(ETK_D9,    INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(3)) 	/* HSUSB1_NXT */

#define USBH2_PADS	\
    PAD_ENTRY(ETK_D14,    INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(3)) /* HSUSB2_D0  */ \
    PAD_ENTRY(ETK_D15,    INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(3)) /* HSUSB2_D1  */ \
	PAD_ENTRY(MCSPI1_CS3, INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(3)) /* HSUSB2_D2  */ \
    PAD_ENTRY(MCSPI2_CS1, INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(3)) /* HSUSB2_D3  */ \
    PAD_ENTRY(MCSPI2_SIMO,INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(3)) /* HSUSB2_D4  */ \
    PAD_ENTRY(MCSPI2_SOMI,INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(3)) /* HSUSB2_D5  */ \
    PAD_ENTRY(MCSPI2_CS0, INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(3)) /* HSUSB2_D6  */ \
	PAD_ENTRY(MCSPI2_CLK, INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(3)) /* HSUSB2_D7  */ \
	PAD_ENTRY(ETK_D10,    INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(3)) /* USB2_CLK   */ \
    PAD_ENTRY(ETK_D11,    INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(3)) /* HSUSB2_STP */ \
    PAD_ENTRY(ETK_D12,    INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(3)) /* HSUSB2_DIR */ \
    PAD_ENTRY(ETK_D13,    INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(3)) /* HSUSB2_NXT */

#define USBOTG_PADS	\
	PAD_ENTRY(USB0_DRVVBUS,	INPUT_ENABLED | PULL_RESISTOR_DISABLED | MUXMODE(0)) /* USB0_DRVBUS */

#define CCDC_CAPTURE_PADS	\
    PAD_ENTRY(CCDC_PCLK,	INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(0)) /* CCDC_PCLK  */ \
    PAD_ENTRY(CCDC_FIELD,   INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(1)) /* CCDC_FIELD  */ \
	PAD_ENTRY(CCDC_HD,		INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(0)) /* CCDC_HD  */ \
    PAD_ENTRY(CCDC_VD,		INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(0)) /* CCDC_DATA8  */ \
    PAD_ENTRY(CCDC_WEN,		INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(1)) /* CCDC_DATA9  */ \
    PAD_ENTRY(CCDC_DATA0,	INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(0)) /* CCDC_DATA0  */ \
    PAD_ENTRY(CCDC_DATA1,	INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(0)) /* CCDC_DATA1  */ \
	PAD_ENTRY(CCDC_DATA2,	INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(0)) /* CCDC_DATA2  */ \
	PAD_ENTRY(CCDC_DATA3,   INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(0)) /* CCDC_DATA3   */ \
    PAD_ENTRY(CCDC_DATA4,   INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(0)) /* CCDC_DATA4 */ \
    PAD_ENTRY(CCDC_DATA5,   INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(0)) /* CCDC_DATA5 */ \
    PAD_ENTRY(CCDC_DATA6,   INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(0)) /* CCDC_DATA6 */ \
	PAD_ENTRY(CCDC_DATA7,   INPUT_ENABLED  | PULL_RESISTOR_DISABLED | MUXMODE(0)) /* CCDC_DATA7 */ \

// Note : this function should be called by bootloaders only !
static _inline void ConfigurePadArray(const PAD_INFO* padArray)
{
    int i=0;
    while (padArray[i].padID != (UINT16) -1)
    {
        SOCSetPadConfig(padArray[i].padID,(UINT16) padArray[i].Cfg);
        i++;
    }
}
